# NUMPY

# I. ARRAY CREATION

## A. CREATING NUMPY ARRAYS

#### 1. This is used to print a single array

In [419]:
import numpy as np
list1 = [10, 20, 30, 40 ,50]
array1 = np.array(list1,dtype = 'float') # It is used to change the complete list's type
print(array1)
type(array1) # It is used to find Type

[10. 20. 30. 40. 50.]


numpy.ndarray

#### 2. This is used to print single array in multiple row

In [420]:
import numpy as np
list2 = [[10, 20], [30, 40], [50, 60]]
array2 = np.array(list2, dtype = 'U32') # "U32" is used to refer string
print(array2)

[['10' '20']
 ['30' '40']
 ['50' '60']]


#### 3. Tis is used to print a ranged numbers

In [421]:
import numpy as np
array3 = np.arange(1, 11)
print(array3)

[ 1  2  3  4  5  6  7  8  9 10]


#### 4. This is used to print ranged number in multiple rows

In [422]:
import numpy as np
array4 = np.arange(1,13).reshape(4, 3)
print(array4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#### 5. This is used to print  0/1 in multiple row

In [423]:
import numpy as np
array5 = np.ones((2,4))
print(array5)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## B. MANIPULATING NUMPY ARRAYS

#### 1.This is used to reshape a data without chancing the data

In [424]:
import numpy as np
array1 = np.arange(1, 10).reshape(3, 3)
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 2. This is used to change the row to column

In [425]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [426]:
array2 = np.reshape(a, (3, 3), order="F")
array2

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

#### 3. This is used to print data in multiple row by repeating the data

In [427]:
import numpy as np
array3 = np.resize(a, (5, 3))
array3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

# II. ARRAY OPERATIONS

## A. MATHEMATICAL OPERATIONS

#### 1. This is used to add, sub, mul, and div two or more array

In [428]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 4, 6, 8, 10])

In [429]:
# ADD

print(arr1 + arr2)

[ 3  6  9 12 15]


In [430]:
# SUB

print(arr1 - arr2)

[-1 -2 -3 -4 -5]


In [431]:
# MUL

print(arr1 * arr2)

[ 2  8 18 32 50]


In [432]:
# DIV

print(arr1 / arr2)

[0.5 0.5 0.5 0.5 0.5]


#### 2.This is used to print column sum, total sum, max, mean, min, varience and root value of varience of an array

In [433]:
import numpy as np
arr3 = np.arange(1,21).reshape(5,4)
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [434]:
sum(arr3)

array([45, 50, 55, 60])

In [435]:
np.sum(arr3)

np.int64(210)

In [436]:
np.max(arr3)

np.int64(20)

In [437]:
np.mean(arr3)

np.float64(10.5)

In [438]:
np.min(arr3)

np.int64(1)

In [439]:
np.var(arr3)

np.float64(33.25)

In [440]:
np.std(arr3) # It is used to find the root value of varience

np.float64(5.766281297335398)

#### 3. This is used to find the trignometry problems like sin, cos, and tan

In [441]:
import numpy as np
arr4 = np.array([0,30,45,60,90])
arr4

array([ 0, 30, 45, 60, 90])

In [442]:
# SIN

np.sin(arr4)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666])

In [443]:
# COS

np.cos(arr4)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362])

In [444]:
# TAN

np.tan(arr4)

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041])

#### 4. This is used to find the exponenetial & logarithms

In [445]:
import numpy as np
arr5 = np.array([1, 2, 3, 4])
arr5

array([1, 2, 3, 4])

In [446]:
# EXPONENTIALS

exp = np.exp(arr5)
print(exp)

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [447]:
# LOGARITHMS

log = np.log(arr5)
print(log)

[0.         0.69314718 1.09861229 1.38629436]


## B. BROADCASTING

#### 1.This is like a matrix addititon, subtraction, multiplication and division

In [448]:
import numpy as np
x = np.arange(1,7).reshape(2,3)
y = np.arange(1,4).reshape(1,3)

In [449]:
# ADDITION

print(x + y)

[[2 4 6]
 [5 7 9]]


In [450]:
# SUBTRACTION

print(x - y)

[[0 0 0]
 [3 3 3]]


In [451]:
# MULTIPLICATION

print(x * y)

[[ 1  4  9]
 [ 4 10 18]]


In [452]:
# DIVISION

print(x / y)

[[1.  1.  1. ]
 [4.  2.5 2. ]]


## C. VECTORIZATION

#### 1. This is used to find the time to complete a loop

In [453]:
import numpy as np
import time

start = time.time()

arr6 = np.array([1, 2, 3, 4, 5])

for i in range(len(arr6)):
    arr6[i] += 20
    
end = time.time()

print("For loop time : ", end - start)


For loop time :  0.0


# III. ARRAY MANIPULATION

## A. SLICING

#### 1. This is used to Slice a array for taking selected number

#### a. Slice one dimension array for print select, skip one number, full number

In [454]:
import numpy as np
ar1 = np.array([1, 2, 3, 4, 5])
ar1

array([1, 2, 3, 4, 5])

In [455]:
# For print selected number
ar1[1:4]

array([2, 3, 4])

In [456]:
# For Skip 1 number
ar1[1::2]

array([2, 4])

In [457]:
# For Full
ar1[ : ]

array([1, 2, 3, 4, 5])

#### b. Slice one dimension array for print selecting row's and column's

In [458]:
import numpy as np
ar2 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [459]:
ar2[1:,1:]
#   ^  ^ -- 'column'
#   |--- 'row'

array([[5, 6],
       [8, 9]])

In [460]:
# For skip a row or column
ar2[::, ::2]

array([[1, 3],
       [4, 6],
       [7, 9]])

# IV. STATISTICAL FUNCTIONS

## A. MEAN

#### 1. This is used to find the avg of the array

In [461]:
import numpy as np
a1 = np.array([1, 2, 3, 4, 5])
print(np.mean(a1))

3.0


# B. MEDIAN

#### 1. This is used to find the avg of the array

In [462]:
import numpy as np
a2 = np.array([1, 2, 8, 9, 5, 4, 6, 7, 3, 10])
print(np.median(a2))

5.5


## C. VARIANCE

#### 1. This is used to find the variance

In [463]:
import numpy as np
a3 = np.array([2, 4, 6, 8, 10, 12])
print(np.var(a3))

11.666666666666666


## D. STANDARD

#### 1. This is used to find the standard

In [464]:
import numpy as np
a4 = np.array([1, 3, 5, 7, 9, 11])
print(np.std(a4))

3.415650255319866


# V. LINEAR ALGEBRA

## A. MATRIX OPERATIONS

#### 1. this is used to print a matrix

In [465]:
import numpy as np
b1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(b1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 2. This is used to add,sub and mul two matrix

In [466]:
import numpy as np
b2 = np.array([
    [3, 2, 1],
    [6, 5, 4],
    [9, 8, 7]
])
print(b2)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [467]:
# add
print(b1 + b2)

[[ 4  4  4]
 [10 10 10]
 [16 16 16]]


In [468]:
# sub
print(b1 - b2)

[[-2  0  2]
 [-2  0  2]
 [-2  0  2]]


In [469]:
# mul
print(np.dot(b1,b2))

[[ 42  36  30]
 [ 96  81  66]
 [150 126 102]]


#### 3.This is used to find the inverse of a matrix

In [470]:
import numpy as np
b3 = np.array([
    [2,5,6],
    [4,9,1],
    [3,5,7]
])
print(np.linalg.inv(b3))

[[-1.1372549   0.09803922  0.96078431]
 [ 0.49019608  0.07843137 -0.43137255]
 [ 0.1372549  -0.09803922  0.03921569]]


#### 4. This is used to multiply element wise

In [471]:
# mul element wise
print(b1 * b2)

[[ 3  4  3]
 [24 25 24]
 [63 64 63]]


## B. EIGEN VALUES

#### 1. This is used to find the eigen values

In [472]:
import numpy as np
b4 = np.array([
    [1,8,6],
    [8,9,5],
    [12,5,9]
])
print(np.linalg.eigvals(b4))

[20.93917372 -5.69562149  3.75644777]


## C. LINEAR EQUATIONS

#### 1. This is used to find the value of two variables in a linear eqns

In [473]:
# 9x + y = 8;
# x + 7y = 15;
import numpy as np
b5 = np.array([[9, 1],[1, 7]])
b6 = np.array([8, 15])
print(np.linalg.solve(b5, b6))


[0.66129032 2.0483871 ]


#### 2. This is used to find the value of three variables in a linear eqns

In [474]:
# 6x + 2y - 5z = 13;
# 3x + 3y - 2z = 13;
# 7x + 5y - 3z = 26;
import numpy as np
b7 = np.array([[6, 2, -5],[3, 3, -2],[7, 5, -3]])
b8 = np.array([13, 13, 26])
print(np.linalg.solve(b7, b8))

[2. 3. 1.]


# VI. RANDOM NUMBER GENERATION

## A. GENERATING RANDOM NUMBERS

#### 1. This is used to print random in different way

In [475]:
# for ranged numbers
from numpy import random
c1 = random.randint(0, 10)
print(c1)

6


In [476]:
# for between 0 and 1
from numpy import random
c2 = random.rand()
print(c2)

0.6344759921168657


In [477]:
# for ranged array
from numpy import random
c3 = random.randint(100, size = (3))
print(c3)

[63 92 16]


In [478]:
# for ranged array
from numpy import random
c4 = random.randint(100, size = (3,5))
print(c4)

[[81 52 75 46 95]
 [29 40 86 13 13]
 [18 68 96 91 93]]


In [479]:
# for selecting given number 
from numpy import random
c5 = random.choice([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(c5)

1
